# La librairie Numpy

### Tableau Numpy vs liste Python

#### Opération arithmetique sur les éléments d’une liste ou plusieurs

In [1]:
liste1 = [1,2,3,4]
liste2 = [5,6,7,8]

In [2]:
# Addition élément par élément de deux listes
[i+j for i,j in zip(liste1,liste2)]

[6, 8, 10, 12]

In [3]:
# Produit élément par élément de deux listes
[i*j for i,j in zip(liste1,liste2)]

[5, 12, 21, 32]

In [9]:
# Multiplication par un scalair
[i*2 for i in liste1]

[2, 4, 6, 8]

Les liste sont plus rapide que les tableaux lorsque vous ajoutez des éléments à la fin

In [11]:
# Ajout d’élément
liste1.append(99)
liste1

[1, 2, 3, 4, 99]

#### Opération arithmetique sur les éléments d’un tableau ou plusieurs

In [102]:
import numpy as np

In [5]:
tab1 = np.array([1,2,3,4])
tab2 = np.array([5,6,7,8])

In [7]:
# Addition élément par élément de deux tableaux
tab1+tab2

array([ 6,  8, 10, 12])

In [8]:
# Produit élément par élément de deux tbleaux
tab1*tab2

array([ 5, 12, 21, 32])

In [10]:
# Multiplication par un scalair
2*tab1

array([2, 4, 6, 8])

Les tableaux sont plus rapide que les listes lorsque l'opération peut être vectorisée

In [13]:
liste3 = [2,1,33,4,5]
np.array(liste3)

array([ 2,  1, 33,  4,  5])

In [14]:
liste3.append(999)

In [15]:
np.array(liste3)

array([  2,   1,  33,   4,   5, 999])

On peut donc trasformé une liste en une tableau 

Les tableaux NumPy ne peuvent pas grandir comme une liste Python : aucun espace n'est réservé à la fin du tableau pour faciliter les ajouts rapides. Il est donc courant de développer une liste Python et de la convertir en un tableau NumPy lorsqu'elle est prête ou de préallouer l'espace nécessaire avec ou : np.zeros  np.empty

In [16]:
np.zeros(4)

array([0., 0., 0., 0.])

In [17]:
np.zeros(4,int)

array([0, 0, 0, 0])

In [18]:
np.empty(4)

array([0., 0., 0., 0.])

In [20]:
a = np.ones(5)
np.zeros_like(a)

array([0., 0., 0., 0., 0.])

In [21]:
a

array([1., 1., 1., 1., 1.])

In [22]:
b = [2,3,2,4,1]
np.ones_like(b)

array([1, 1, 1, 1, 1])

In [23]:
b

[2, 3, 2, 4, 1]

In [24]:
np.full_like(b,8)

array([8, 8, 8, 8, 8])

Donc la fonction full_like(tableau,valeur) remplace tous les éléments du tableau par la valeur "valeur"

In [ ]:
np.empty_like(b)

#### Il existe jusqu'à deux fonctions pour l'initialisation d'un tableau avec une séquence monotone dans NumPy :

arange(start,stop,step)  ou linspace(start,stop,num)

In [34]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [35]:
np.arange(2,5)

array([2, 3, 4])

In [37]:
np.arange(2,10,3)

array([2, 5, 8])

In [52]:
np.linspace(0,2,6)

array([0. , 0.4, 0.8, 1.2, 1.6, 2. ])

### Générer des tableaux aléatoires

np.random.randint(debut,fin,nombre_element), genère un tableau contenant "nombre_element" élément dont les valeurs sont aléatoire et comprisent entre "debut" et "fin"  

np.random.uniform(debut,fin,nombre_element), genère un tableau contenant "nombre_element" valeur suivant la loi uniforme et comprise entre "debut" et "fin"

np.random.normal(a,b,c) , genère un tableau contenant c valeur suivant la loi normale de moyenne a et d’écat-type b

np.random.randn(n),  genère un tableau contenant n valeur suivant la loi normale centrée reduite

In [53]:
np.random.randint(1,20,5)

array([19, 12, 18,  8, 13])

In [59]:
np.random.uniform(1,10,3)

array([4.39505372, 4.94158927, 8.4710388 ])

In [60]:
np.random.normal(5,2,4)

array([7.32937447, 3.24989277, 2.42430377, 6.98526481])

In [61]:
np.random.randn(5)

array([ 0.72503601,  0.8816751 , -1.08272771, -0.79799888,  1.03734535])

Il existe également une nouvelle interface pour la génération de tableaux aléatoires. Il est :

    – mieux adapté au multi-threading,

    – un peu plus rapide,

    – plus configurable (vous pouvez obtenir encore plus de vitesse ou encore plus de qualité en choisissant un soi-disant « 
    générateur de bits » non par défaut),

    – capable de passer deux étapes délicates tests synthétiques que l'ancienne version échoue.
    
   rng = np.random.delault_rng()

In [63]:
rng = np.random.default_rng()

In [70]:
rng.integers(0,10,3) # valeur alea entière comprise entre 0 et 10 , nombre élément est 3

array([7, 5, 3], dtype=int64)

In [71]:
rng.random(4)  # valeur alea comprise entre 0 et 1

array([0.5175445 , 0.36325905, 0.45665737, 0.96372889])

In [72]:
rng.standard_normal(4) # avec des valeurs suivant la loi normale centré reduite

array([ 1.1489923 , -1.31812214,  0.02031407, -0.38174745])

In [73]:
rng.normal(5,2,4) # avec des valeurs suivant la loi normale de myenne 5 d’écart-type 2 

array([8.57299603, 5.21715286, 1.18207656, 3.53984819])

In [75]:
rng.uniform(0,10,3) # avec des valeurs suivant la loi uniforme comprise entre 0 et 10

array([7.46975931, 2.74674712, 6.24074966])

### Indexation vectorielle
Une fois que vous avez vos données dans le tableau, NumPy est génial pour fournir des moyens simples de les restituer :

In [77]:
# Exemple :
a = np.arange(1,8)
a

array([1, 2, 3, 4, 5, 6, 7])

In [79]:
a[1] # a[i] permer d’acceder à l’élément qui se trouve à l’indice i (à la position i+1)

2

In [80]:
a[3:] # de l’indice i jusqu’a la fin du tableau

array([4, 5, 6, 7])

In [81]:
a[-2] # avec l’indice negative 

6

In [82]:
a[-2:]

array([6, 7])

In [84]:
a[2:6] 

array([3, 4, 5, 6])

Toutes ces méthodes, y compris l'indexation sophistiquée, sont modifiables : elles permettent de modifier le contenu du tableau d'origine par affectation, comme indiqué ci-dessous. Cette fonctionnalité rompt avec l'habitude de copier des tableaux en les découpant :

In [85]:
a

array([1, 2, 3, 4, 5, 6, 7])

In [87]:
a[0] = 99
a

array([99,  2,  3,  4,  5,  6,  7])

In [89]:
a[5:] = 88
a

array([99,  2,  3,  4,  5, 88, 88])

In [91]:
d = a.copy()
d

array([99,  2,  3,  4,  5, 88, 88])

In [93]:
a[0] = 111
a

array([111,   2,   3,   4,   5,  88,  88])

In [94]:
d

array([99,  2,  3,  4,  5, 88, 88])

In [96]:
c = np.arange(5)
c

array([0, 1, 2, 3, 4])

In [98]:
c[0:3] = [9,9,9]
c

array([9, 9, 9, 3, 4])

Un autre moyen très utile d'obtenir des données à partir de tableaux NumPy est l'indexation booléenne, qui permet d'utiliser toutes sortes d'opérateurs logiques :

In [99]:
a = np.array([1,2,3,4,5,6,7,8,7,6,5,4,3,2,1])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 7, 6, 5, 4, 3, 2, 1])

In [100]:
np.any(a>7) # S’il existe au moins un élément de a qui superieur à 7

True

In [101]:
np.any(a>8) # S’il existe au moins un élément de a qui superieur à 8

False

In [105]:
np.all(a > 2) # Si tout les éléments de a sont superieur à 2

False

In [103]:
np.all(a >= 0) # Si tout les éléments de a sont superieur à 0 (ou positive)

True

In [104]:
a[a > 4] # les éléments de a qui sont strictement superieur à 4

array([5, 6, 7, 8, 7, 6, 5])

In [106]:
a[a>6] = 0 # remplace tous les eléments de a qui sont strictement superieur à 6
a

array([1, 2, 3, 4, 5, 6, 0, 0, 0, 6, 5, 4, 3, 2, 1])

On peut utilisé les opérateurs logiques (&, |, ^, ~)

    Attention cependant
    Les comparaisons Python "ternaires" comme 3 <= a <= 5 ne fonctionnent pas ici.

In [107]:
a[(a > 2) & (a <= 5)] = 11 # L’operateur logique & (et ou intersection en théorie des groupes)
a

array([ 1,  2, 11, 11, 11,  6,  0,  0,  0,  6, 11, 11, 11,  2,  1])

In [113]:
b = np.array([1,2,3,4,5,6,66,7,8,7,66,54,3,2,1,1,0])

In [116]:
np.where(b > 2)

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int64),)

In [133]:
b = np.array([1,2,3,4])
c = np.array([2,2,4,4])

In [118]:
np.sqrt(b) # la racine de chaque élément du tableau

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [119]:
np.exp(b) # la racine de chaque élément du tableau

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [122]:
b/c

array([0.5 , 1.  , 0.75, 1.  ])

In [123]:
b/2

array([0.5, 1. , 1.5, 2. ])

In [130]:
np.log(b)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [131]:
np.dot(b,c) # le produit scalaire de b et c 

34

In [136]:
np.cross([1,2,3],[2,1,1])  # produit vectorielle

array([-1,  5, -3])

In [137]:
np.sin([np.pi,np.pi/2])  # fonction trogonometrique sur les tableau

array([1.2246468e-16, 1.0000000e+00])

### Les tableaux peuvent être arrondis dans leur ensemble :

In [139]:
np.round(np.sin([np.pi,np.pi/2]),3) # la fonction round pour arondir

array([0., 1.])

In [142]:
a = np.array([1.212,4.32112,3.45,5.89])

In [143]:
np.round(a)

array([1., 4., 3., 6.])

In [144]:
np.round(a,1)

array([1.2, 4.3, 3.4, 5.9])

In [145]:
np.floor(a)   #c’est la partie entière de a

array([1., 4., 3., 5.])

In [146]:
np.ceil(a)   

array([2., 5., 4., 6.])

### NumPy est également capable de faire les statistiques de base :

In [22]:
a = np.array([1,2,3,4,5,6,7,8,9,10])

In [6]:
a.max() # ou max(a) 

10

In [8]:
min(a)

1

In [10]:
np.std(a)

2.8722813232690143

In [11]:
np.var(a)

8.25

In [12]:
np.sum(a)

55

In [13]:
np.argmax(a)

9

In [14]:
np.argmin(a)

0

In [15]:
np.mean(a)

5.5

In [16]:
np.std(a,ddof = 1)

3.0276503540974917

## Matrices, les tableaux 2D

In [24]:
# La syntaxe d'initialisation de la matrice est similaire à celle des vecteurs :
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
np.full((3,4),9)

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])

In [33]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [35]:
np.empty((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [38]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

La génération de matrices aléatoires est également similaire à celle des vecteurs :

In [39]:
np.random.randint(0,20,(4,4))

array([[ 0,  9,  8, 14],
       [ 3,  5,  1, 11],
       [ 9,  0,  3,  1],
       [ 0, 10, 19, 18]])

In [41]:
np.random.uniform(0,10,(3,3))

array([[3.92842545, 1.8195207 , 6.17447604],
       [2.37402603, 1.14119674, 7.89142945],
       [2.85523668, 8.43891296, 3.96322372]])

In [42]:
np.random.normal(4,2,(3,3))

array([[2.82640317, 5.84640477, 3.83071435],
       [1.2424498 , 1.60053015, 5.8841483 ],
       [2.26490511, 6.26093351, 3.27709286]])

In [44]:
np.random.randn(3,4) # normale centrée reduite

array([[ 2.29644418,  0.61730525, -0.27819544, -0.20128989],
       [ 1.2283908 , -1.85094677, -0.67343028,  0.21959899],
       [-0.1372467 ,  1.04810754, -0.76238653,  0.44729308]])

In [47]:
rng = np.random.default_rng()

In [48]:
rng.integers(1,5,(3,3))

array([[4, 4, 1],
       [2, 1, 1],
       [3, 1, 2]], dtype=int64)

In [53]:
rng.standard_normal((4,3)) 

array([[ 0.49676454, -1.07531407,  0.4224594 ],
       [-0.36135058,  0.92182593, -0.02723534],
       [ 0.70451069,  0.08994827, -1.12545256],
       [ 0.24472182,  0.12594527, -0.54105   ]])

In [54]:
rng.normal(3,2,(2,2))

array([[0.94808746, 2.70136481],
       [1.27593136, 8.63578458]])

### L'argument de l'axe
Dans de nombreuses opérations (par exemple, sum), vous devez indiquer à NumPy si vous souhaitez opérer sur des lignes ou des colonnes.

Pour avoir une notation universelle qui fonctionne pour un nombre arbitraire de dimensions, NumPy introduit une notion d'axe : 

La valeur de l' axisargument est en fait le numéro de l'indice en question : Le premier indice est axis=0, le second est axis=1, et ainsi de suite. Donc, en 2D axis=0, c'est par colonne et axis=1signifie par ligne.

In [57]:
a = np.array([[1,2,3],[1,1,1],[4,5,6]])
a

array([[1, 2, 3],
       [1, 1, 1],
       [4, 5, 6]])

In [58]:
a.sum(axis =0)

array([ 6,  8, 10])

In [59]:
a.sum(axis = 1)

array([ 6,  3, 15])

In [60]:
a.max(axis = 0)

array([4, 5, 6])

In [61]:
a.min(axis = 0)

array([1, 1, 1])

### Arithmétique matricielle
En plus des opérateurs ordinaires (comme +, -,*, /, // et **) qui fonctionnent élément par élément, il existe un opérateur @ qui calcule un produit matriciel 

In [69]:
a = np.array([[1,2,3],[4,5,6],[1,0,2]])
b = np.array([[2,2,2],[1,2,1],[3,3,1]])

In [70]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [1, 0, 2]])

In [71]:
b

array([[2, 2, 2],
       [1, 2, 1],
       [3, 3, 1]])

In [72]:
a+b

array([[3, 4, 5],
       [5, 7, 7],
       [4, 3, 3]])

In [73]:
a*b

array([[ 2,  4,  6],
       [ 4, 10,  6],
       [ 3,  0,  2]])

In [74]:
a@b

array([[13, 15,  7],
       [31, 36, 19],
       [ 8,  8,  4]])

In [75]:
a**b

array([[ 1,  4,  9],
       [ 4, 25,  6],
       [ 1,  0,  2]], dtype=int32)

#### Vecteurs lignes et vecteurs colonnes
Comme le montre l'exemple ci-dessus, dans le contexte 2D, les vecteurs ligne et colonne sont traités différemment. 

Cela contraste avec la pratique habituelle de NumPy d'avoir un type de tableaux 1D dans la mesure du possible (par exemple, a[:,j]- la jème colonne d'un tableau 2D a- est un tableau 1D).

Par défaut, les tableaux 1D sont traités comme des vecteurs de ligne dans les opérations 2D, donc lors de la multiplication d'une matrice par un vecteur de ligne, vous pouvez utiliser la forme (n,) ou (1, n) - le résultat sera le même. 

Si vous avez besoin d'un vecteur colonne, il existe plusieurs façons de le préparer à partir d'un tableau 1D, mais étonnamment transpose, ce n'en est pas une 

In [76]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [1, 0, 2]])

In [81]:
a.transpose()

array([[1, 4, 1],
       [2, 5, 0],
       [3, 6, 2]])

In [82]:
c = np.array([[1,2,3],[5,6,7]])
c

array([[1, 2, 3],
       [5, 6, 7]])

In [83]:
c.transpose()

array([[1, 5],
       [2, 6],
       [3, 7]])

Deux opérations capables de créer un vecteur colonne 2D à partir d'un tableau 1D sont le remodelage et l'indexation avec newaxis :

In [85]:
a = np.array(range(6))
a

array([0, 1, 2, 3, 4, 5])

In [86]:
a.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [94]:
a.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [95]:
d = np.array([12,1,2,3,4,1111,3,45,6,7,8,9])
d

array([  12,    1,    2,    3,    4, 1111,    3,   45,    6,    7,    8,
          9])

In [96]:
np.where(d>3)

(array([ 0,  4,  5,  7,  8,  9, 10, 11], dtype=int64),)

### #L'argument de l'axe
Dans de nombreuses opérations (par exemple, la somme), vous devez indiquer à NumPy si vous souhaitez opérer sur des lignes ou des colonnes. 

Pour avoir une notation universelle qui fonctionne pour un nombre arbitraire de dimensions, NumPy introduit une notion d'axe: La valeur de l'argument axe est en fait le numéro de l'indice en question: Le premier indice est axis=0 , le second est axis=1, et ainsi de suite.

Ainsi, en 2D, l'axe = 0 correspond à la colonne et l'axe = 1 correspond à la ligne.



In [104]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [105]:
a.sum() # ici c’est la somme de tous les éléments de a

136

In [107]:
a.sum(axis = 0) 

array([28, 32, 36, 40])

In [108]:
a.sum(axis = 1)

array([10, 26, 42, 58])

In [109]:
a.mean() # ici c’est la moyenne de tous les élélements de a

8.5

In [111]:
a.mean(axis = 0)

array([ 7.,  8.,  9., 10.])

#### Manipulations matricielles
Il existe deux fonctions principales pour joindre les tableaux :

In [129]:
b = np.array(list(range(17,33)))
b = b.reshape(4,4)

In [126]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [130]:
np.hstack((a,b)) # De manière horizontale

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [131]:
np.vstack((a,b)) # De manière verticale

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

### 3D 
Lorsque vous créez un tableau 3D en remodelant un vecteur 1D ou en convertissant une liste Python imbriquée, la signification des indices est (z,y,x).

Le premier indice est le numéro du plan, puis les coordonnées vont dans ce plan :

In [148]:
#Exemple:
d = np.arange(1,65).reshape(4,4,4)
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]],

       [[33, 34, 35, 36],
        [37, 38, 39, 40],
        [41, 42, 43, 44],
        [45, 46, 47, 48]],

       [[49, 50, 51, 52],
        [53, 54, 55, 56],
        [57, 58, 59, 60],
        [61, 62, 63, 64]]])